#!/bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: $0 <libexec-path, when running manually use '.'> device rate ppm <listen-address, default ::1> [<port, default 4444>]"
  exit 2
fi

sdr="/tmp/sdrpipe$$"
tune="/tmp/tunepipe$$"
gain="30"
libexec_path="$1"
device="$2"
sample_rate="$3"
ppm="$4"
listen_address="$5"
listen_port="$6"

if [ -z $listen_address ]; then
  listen_address="::1"
fi

if [ -z $listen_port ]; then
  listen_port="4444"
fi

freq="$(( 100 * 1000 * 1000 ))"

[ ! -p "$sdr" ] && mkfifo "$sdr"
[ ! -p "$tune" ] && mkfifo "$tune"

# set -b :: for ipv4 and ipv6 all interfaces
$libexec_path/server -p "$ppm" -f "$freq" -i "$tune" -o "$sdr" -f "$freq" -g "$gain" -a -s "$sample_rate" -b "$listen_address" -t $listen_port -w 1024 &
spid=$!

echo "Server PID $spid, use 'gdb ./server $spid -ex c' to debug"

trap "kill $spid; rm -f $sdr $tune" SIGINT SIGTERM exit

$libexec_path/osmosdr-input.py -d "$device" -r "$sample_rate" -i "$tune" -o "$sdr" -f "$freq" -g "$gain" -p "$ppm"
